apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/james-rotary/todo-config.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-prod
  syncPolicy:
    # Production: Manual sync for safety
    syncOptions:
      - CreateNamespace=true