---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-database-secret
  namespace: todo-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBovTkjHDp8F3Se2lg3eyuuErn31zK1GQ4uLrGiig/lDG+ijvHmqeJKcjBN+9BJaMHB/hIvLQDCMaaEbwwjJLOtYFzSfrwoUn9kyfKhlCvYoUQ2z3+mf281gGjNI2kw/OPQGHX9kOd0SteeGB3+5eOTdp1k094i2BsY2IeTcgN4jG8aclScoOzXWYycPAwY1HFSWNxDQZD+BEly0ReX61BofGcmRMb6ADDjTI9Dr0EdfTtgXzQS4m1ZsGVOVESyCw27S91EA4JtIZTTPookOjbRaaOIJQj8bf2EcKLusZ0VYQiNjz1aF9QuP75EmyXaexjHzfg0pHl1zca08Z5GK3pgZyJx9CccXPgB2jW+B8pm42yWUWNIbuZL7zY3FmA7gwyfrlDWXkvrzaJLqTZicXj7Ftd5pXAPqZNn+ikqej1qRfM4j6scwHXVXbkf+zcj+qzrCNxmXuYHNuuRJuZ9yGR40tbsWAsdALZ7JCuoiKmF4Io0JF+pMcPMOFaSqJC8hrdSaRdcdcrDJgnze5Rigkc40K/3qm82JEWxc72o50B14JXWG+DYbUI4f2uj2hdzTTwMqfFBNG2fmeSbduswkadLLGALG1xFs55lG/ozlQIrGpQmqwrrMU3DPdSG+7+jZB38VmwwINQP4jJY5q7PO/Z6Ut8X4IICiLib8neCA1q4HEB2HxUDRJ8C43st2TLmDqVuTDdk
    POSTGRES_USER: AgBlg2XLWxQqhKfNoK55f7BShO0enb0CLhSrktcxkCrmm7LX4gajt/I5jg2wYecVUbOfcXZN9Cr0hK8eyRcPzhYF4f44GTSgFnDWHRPNWX1UZLEC0SIhoUyOv9cN3vV0ejNdQzhsU4n0o0RJfTA44FjAOonZrBaXQXQp4s1nPxouXlVPwGWNPv7AgjzUtaqtKIbTc4U1DcdUNg76UJN7lL4k3UxUc9e1lYYxm0dAP6AgwRCgE0HFxUwcXDO1+I43QuoE5slAYDjSkrthose6wSXBZxnEzLKbEtDEkkJLrXpjuifbAy8CKrW+nMptWs+csGfR7IEvOVmCjScyusILM8ULRTA3sbE/rf0glVvJYfZtdWoTKOGwWQEnoVpeE9J6gMo/6WU0wgtAXxIZOf9umJHEKfPXcZWGsLNZmOpKVyWH0ldL5Lf/IqpjHxXraZssRg1CiBwLhgtDps9YEg7PQIKnQZtpJiJhitSq9pYFxtlEh37noLP2MKE6rgA4o9OvgF6Q73sAcxsu3gSGE51mDJ61kWtJ9+weRk1CCisef3AbfNRnaDb6e/2x7nk7tk+U+7PKOfvW2Gy3f+Ie7gWawybh7aG375d9svpedtzQAzksaGk/U8P+QEZb1jVdsPl6tNf8I5AFYrZQmEhUzUpW3E3gHWvuJPMyWCMicG7xFk6uPVhxSy/UHE7YXeR9c+lGu1XF+Sw5
  template:
    metadata:
      name: todo-database-secret
      namespace: todo-dev
