apiVersion: v1
kind: Service
metadata:
  name: todo-database
spec:
  selector:
    app: todo-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP