apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-prod

resources:
  - ../../base

patchesStrategicMerge:
  - patch-backend-deployment.yaml
  - patch-frontend-deployment.yaml
  - patch-services.yaml

images:
  - name: ghcr.io/you/todo-backend
    newTag: prod-latest
  - name: ghcr.io/you/todo-frontend  
    newTag: prod-latest