apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: NODE_ENV
              value: production