apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: API_BASE_URL_INTERNAL
              value: http://todo-backend:8080