apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080